// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using NotesWebApplication.Models;

namespace NotesWebApplication.Migrations
{
    [DbContext(typeof(NotesContext))]
    internal class NotesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NotesWebApplication.Models.Note", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Data");

                b.Property<string>("DeleteToken");

                b.Property<bool>("Destroying");

                b.Property<string>("StringId");

                b.Property<bool>("SyntaxHighlighting");

                b.HasKey("Id");

                b.ToTable("Notes");
            });
#pragma warning restore 612, 618
        }
    }
}